= SCMA Google Calendar

image::https://github.com/rfdonnelly/scma-gcal/workflows/Update%20Google%20Calendar/badge.svg[Update Google Calendar]

Fetches events from the SCMA (Southern California Mountaineer's Association) website and exports them to Google Calendar.

== Install

Run:

 bundle install

== Setup

For the Google Calendar export feature, you need to first create a calendar named "SCMA".
Events will be exported to this calendar.

Next, follow "Step 1: Turn on the Google Calendar API" of the link:https://developers.google.com/calendar/quickstart/ruby[Google Calendar API Ruby Quickstart].
Then run `scma-gcal` interactively with the `--output gcal` option and follow the instructions to generate a `token.yml` file. 

== Examples

=== Web to GCal

Fetches events from the SCMA website and imports them into Google Calendar.

 scma-gcal -u <scma-username> -p <scma-password> -o gcal

=== Web to YAML

Fetches events from the SCMA website and converts them to YAML.

 scma-gcal -u <scma-username> -p <scma-password> -o yaml > events.yml

=== YAML to GCal

Reads events from a YAML file and import them into Google Calendar.

 scma-gcal -i yaml -f events.yml -o gcal
