#!/usr/bin/env ruby
# Scrapes list of SCMA (Southern California Mountaineers Association) events 
# and converts to CSV for import into Google Calendar.
#
# Note: Does not handle duplicates.  If you import same event multiple times,
# you will get multiple of the same event.

require_relative 'lib/scma_gcal'

SCMAGCal::Application.new.run(ARGV)
