#!/usr/bin/env ruby
# Scrapes list of SCMA (Southern California Mountaineers Association) events 
# and converts to CSV for import into Google Calendar.
#
# Note: Does not handle duplicates.  If you import same event multiple times,
# you will get multiple of the same event.
#
# Usage:
# scma_events <username> <password>

require 'mechanize'
require 'date'

require_relative 'lib/scma_gcal/model/event'
require_relative 'lib/scma_gcal/input/web'
require_relative 'lib/scma_gcal/output/csv'
require_relative 'lib/scma_gcal/core_extensions'

String.include CoreExtensions::String::RemoveNBSP
String.include CoreExtensions::String::CollapseWhitespace
MatchData.include CoreExtensions::MatchData::ToHash

def main
  username, password = ARGV

  input = Web.new(username, password)

  events = input.events

  CSV.new.write(events)
end

main
